Oбрабатывает действия пользователя в полях «Тип жилья» и «Время заезд…
htmlacademy-javascript/1685521-keksobooking-24 pull request #8
Opened 2021-10-30 18:26 UTC by evgeniy-br

…а-выезда»

2021-10-31 17:09 UTC, Dima-Dim requested changes
Нужно решить конфликт https://github.com/htmlacademy-javascript/1685521-keksobooking-24/pull/8

2021-11-01 06:16 UTC, Dima-Dim commented on js/user-form.js
> +typeOfHousingSelect.addEventListener('input', () => {
После того как дойдёшь до конца проекта не забудь проверить не будут ли копистся эти обработчики после отправки форм.

2021-11-01 06:16 UTC, merged

2021-11-01 11:24 UTC, evgeniy-br commented on js/user-form.js
> +typeOfHousingSelect.addEventListener('input', () => {
А что это значит? Где копиться?

2021-11-01 12:39 UTC, Dima-Dim commented on js/user-form.js
> +typeOfHousingSelect.addEventListener('input', () => {
Значит утечку памяти. Копятся на dom-элементах. Вам должны были рассказывать об этом на лайвах.